This is the exmaple of forward pass of RNN using numpy build from scratch.

In [1]:
import numpy as np


In [2]:
#input sequence of length 5
x1 = np.random.rand(5)
x2 = np.random.rand(5)
x3 = np.random.rand(5)

print(x1)
print(x2)
print(x3)

[0.33520672 0.40517413 0.0691529  0.04604823 0.34457955]
[0.85862311 0.38620531 0.64498286 0.37735787 0.00964923]
[0.7257879  0.52960445 0.0877727  0.5002307  0.41135378]


In [3]:
#hidden size of 4
h0 = np.random.rand(4)

#initialize weights 
Wxh = np.random.rand(4,5)#input to hidden
Whh = np.random.rand(4,4)#hidden to hidden
Why = np.random.rand(1,4)#hidden to output
bh = np.random.rand(4)#hidden bias

print(Wxh)
print(Whh)
print(Why)
print(bh)


[[0.43265904 0.4474946  0.10844399 0.51003486 0.7493506 ]
 [0.10154414 0.83561331 0.21975971 0.44911768 0.54269103]
 [0.12047603 0.18319152 0.55865233 0.68914667 0.75844586]
 [0.34134011 0.17453697 0.68300814 0.77965051 0.65234159]]
[[0.54716062 0.39908791 0.62646519 0.39264237]
 [0.37307689 0.27853404 0.61388681 0.80867975]
 [0.2711872  0.66154076 0.61761121 0.9651251 ]
 [0.99277598 0.07943479 0.47703747 0.62451755]]
[[0.93918506 0.71973289 0.10819562 0.72065742]]
[0.6326499  0.38262663 0.1512654  0.84327321]


In [4]:
#input contribution
def input_contribution(x, Wxh):
    return np.dot(Wxh, x)

#hidden contribution
def hidden_contribution(h, Whh):
    return np.dot(Whh, h)

#add bias
def add_bias(contribution, b):
    return contribution + b

#apply activation function (tanh)
def apply_activation(x):
    return np.tanh(x)

In [5]:
# List to store hidden states and outputs
hidden_states = []
outputs = []

# Forward pass for 3 time steps
for t in range(3):
    # Select input and previous hidden state
    if t == 0:
        x = x1
        h_prev = h0
    elif t == 1:
        x = x2
        h_prev = h1
    else:
        x = x3
        h_prev = h2

    # Compute contributions
    input_contr = input_contribution(x, Wxh)
    hidden_contr = hidden_contribution(h_prev, Whh)
    total_contr = add_bias(input_contr + hidden_contr, bh)
    h_new = apply_activation(total_contr)

    # Store hidden state
    hidden_states.append(h_new)

    # Compute output
    y_t = Why @ h_new  # shape (1,)
    outputs.append(y_t)

    print(f"Hidden state at time step {t+1}: {h_new}")
    print(f"Output at time step {t+1}: {y_t}")

    # Update variables for next step
    if t == 0:
        h1 = h_new
    elif t == 1:
        h2 = h_new


Hidden state at time step 1: [0.948302   0.92891707 0.87720866 0.95792852]
Output at time step 1: [2.34445168]
Hidden state at time step 2: [0.99706793 0.99538535 0.99723441 0.99929737]
Output at time step 2: [2.48089035]
Hidden state at time step 3: [0.9988178  0.99792765 0.99835349 0.99941745]
Output at time step 3: [2.4845712]
