This is the exmaple of forward pass of RNN using numpy build from scratch.

In [2]:
import numpy as np


In [8]:
#input sequence of length 5
x1 = np.random.rand(5)
X2 = np.random.rand(5)
x3 = np.random.rand(5)

print(x1)
print(X2)
print(x3)

[0.90640937 0.25144506 0.30602158 0.35251917 0.2765046 ]
[0.02651162 0.4145215  0.71075841 0.82752599 0.63591166]
[0.52509847 0.4817323  0.70406985 0.93538325 0.77301074]


In [11]:
#hidden size of 4
h0 = np.random.rand(4)

#initialize weights 
Wxh = np.random.rand(4,5)#input to hidden
Whh = np.random.rand(4,4)#hidden to hidden
Why = np.random.rand(1,4)#hidden to output
bh = np.random.rand(4)#hidden bias

print(Wxh)
print(Whh)
print(Why)
print(bh)


[[0.7411311  0.74444976 0.76916484 0.48900361 0.50741082]
 [0.38797286 0.16337669 0.31563708 0.78982983 0.36984504]
 [0.39842816 0.40204793 0.56579654 0.40089312 0.76486668]
 [0.85007705 0.97423885 0.28613735 0.52566306 0.6497146 ]]
[[0.74871049 0.55513718 0.1386909  0.3102115 ]
 [0.56880317 0.07689419 0.54535851 0.40164385]
 [0.07506474 0.10031359 0.83000746 0.72687832]
 [0.32550173 0.42827915 0.46443667 0.89306524]]
[[0.44278221 0.16416181 0.4906325  0.11914948]]
[0.90844374 0.39502374 0.31686974 0.23232417]


In [12]:
#input contribution
def input_contribution(x, Wxh):
    return np.dot(Wxh, x)

#hidden contribution
def hidden_contribution(h, Whh):
    return np.dot(Whh, h)

#add bias
def add_bias(contribution, b):
    return contribution + b

#apply activation function (tanh)
def apply_activation(x):
    return np.tanh(x)

In [13]:
#forward pass for one time step
for t in range(3):
    if t == 0:
        x = x1
        h_prev = h0
    elif t == 1:
        x = X2
        h_prev = h1
    else:
        x = x3
        h_prev = h2

    input_contr = input_contribution(x, Wxh)
    hidden_contr = hidden_contribution(h_prev, Whh)
    total_contr = add_bias(input_contr + hidden_contr, bh)
    h_new = apply_activation(total_contr)

    print(f"Hidden state at time step {t+1}: {h_new}")

    if t == 0:
        h1 = h_new
    elif t == 1:
        h2 = h_new

Hidden state at time step 1: [0.99436474 0.9522281  0.97227259 0.98829198]
Hidden state at time step 2: [0.99957249 0.99634993 0.99781849 0.99895021]
Hidden state at time step 3: [0.99986379 0.99823147 0.99902654 0.99972783]
