This is the exmaple of forward pass of RNN using numpy build from scratch.

In [2]:
import numpy as np


In [15]:
#input sequence of length 5
x1 = np.random.rand(5)
x2 = np.random.rand(5)
x3 = np.random.rand(5)

print(x1)
print(X2)
print(x3)

[0.49903301 0.52215868 0.17168928 0.68472464 0.32821486]
[0.02651162 0.4145215  0.71075841 0.82752599 0.63591166]
[0.91580696 0.16550636 0.94492767 0.57154826 0.23019508]


In [16]:
#hidden size of 4
h0 = np.random.rand(4)

#initialize weights 
Wxh = np.random.rand(4,5)#input to hidden
Whh = np.random.rand(4,4)#hidden to hidden
Why = np.random.rand(1,4)#hidden to output
bh = np.random.rand(4)#hidden bias

print(Wxh)
print(Whh)
print(Why)
print(bh)


[[0.99862567 0.43972088 0.75690413 0.09419296 0.70101192]
 [0.49367026 0.4493218  0.23353962 0.09604485 0.19062771]
 [0.72607533 0.83342003 0.97089688 0.1787825  0.86078067]
 [0.85189069 0.48746139 0.35410058 0.98493487 0.80608753]]
[[0.72446344 0.90283942 0.48465587 0.32842052]
 [0.87142847 0.78641653 0.67418201 0.57091063]
 [0.73427618 0.12769346 0.85273507 0.20675286]
 [0.39808069 0.78208331 0.53399041 0.14971252]]
[[0.75078494 0.41339503 0.11346211 0.98999982]]
[0.35166491 0.93337317 0.91410564 0.65210589]


In [17]:
#input contribution
def input_contribution(x, Wxh):
    return np.dot(Wxh, x)

#hidden contribution
def hidden_contribution(h, Whh):
    return np.dot(Whh, h)

#add bias
def add_bias(contribution, b):
    return contribution + b

#apply activation function (tanh)
def apply_activation(x):
    return np.tanh(x)

In [18]:
# List to store hidden states and outputs
hidden_states = []
outputs = []

# Forward pass for 3 time steps
for t in range(3):
    # Select input and previous hidden state
    if t == 0:
        x = x1
        h_prev = h0
    elif t == 1:
        x = x2
        h_prev = h1
    else:
        x = x3
        h_prev = h2

    # Compute contributions
    input_contr = input_contribution(x, Wxh)
    hidden_contr = hidden_contribution(h_prev, Whh)
    total_contr = add_bias(input_contr + hidden_contr, bh)
    h_new = apply_activation(total_contr)

    # Store hidden state
    hidden_states.append(h_new)

    # Compute output
    y_t = Why @ h_new  # shape (1,)
    outputs.append(y_t)

    print(f"Hidden state at time step {t+1}: {h_new}")
    print(f"Output at time step {t+1}: {y_t}")

    # Update variables for next step
    if t == 0:
        h1 = h_new
    elif t == 1:
        h2 = h_new


Hidden state at time step 1: [0.99317918 0.995914   0.99729756 0.9973296 ]
Output at time step 1: [2.25788148]
Hidden state at time step 2: [0.9975533  0.99942707 0.99844167 0.99862605]
Output at time step 2: [2.26403109]
Hidden state at time step 3: [0.99983664 0.99982706 0.99987811 0.99973129]
Output at time step 3: [2.26716791]
